development:
  adapter: postgresql
  encoding: unicode
  database: ls_test_project_dev
  pool: 5
  username: MetadoX
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: ls_test_project_dev
  tool: 5
  username: MetadoX
  password:

cucumber:
  <<: *test
  username: MetadoX
  password:

