source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.1'
ruby '2.0.0'

# Use sqlite3 as the database for Active Record
#gem 'sqlite3'

# Postgress Adapter
gem 'pg'

# A helper for creating declarative interfaces in controllers
# http://www.decentexposure.info
gem 'decent_exposure'

# OmniAuth is a flexible authentication system utilizing Rack middleware
gem 'omniauth'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# HTML Abstraction Markup Language - A Markup Haiku http://haml.info
gem 'haml'

# Twitter Bootstrap 3.1.1 for Rails Asset Pipeline
gem 'twitter-bootstrap-rails'

# Forms made easy for Rails! It's tied to a simple DSL, with no opinion on markup
gem 'simple_form'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

group :development, :test do
  # Use debugger
  gem 'debugger'

  # Better error page for Rails and other Rack apps
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'cucumber-rails', :require => false, git: 'https://github.com/cucumber/cucumber-rails.git'
  gem 'selenium-webdriver'
  gem 'awesome_print'
end
