source 'https://rubygems.org'

gem 'rails', '4.0.1'
ruby '2.0.0'
gem 'pg'
gem 'decent_exposure'
gem 'devise'
gem 'omniauth'
gem 'sass-rails', '~> 4.0.0'
gem 'haml'
gem 'twitter-bootstrap-rails'
gem 'simple_form'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'bcrypt-ruby', '~> 3.1.2'
gem 'carrierwave'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :development, :test do
  gem 'debugger'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'cucumber-rails', :require => false, git: 'https://github.com/cucumber/cucumber-rails.git'
  gem 'selenium-webdriver'
  gem 'awesome_print'
end
